CREATE TABLE IF NOT EXISTS shop_werte (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    shop INT NOT NULL,
    schlussel VARCHAR(512) NOT NULL,
    inhalt TEXT NOT NULL,
    FOREIGN KEY (shop) REFERENCES shop(id)
);