name: Shopy
version: 1
main: de.dome.shopy.Shopy
author: Dev_Dome
description: Kommt später
authors: [Dev_Dome]
depend: [PlayerNPC]
api-version: '1.20'
commands:
  setspawn:
  LoadDefaultValue:
  setnpcspawn:
  shop:
  spawn:
  setshopzone:
  ressouren:
  money:
  setRessource: