name: Shopy
version: 1
main: de.dome.shopy.Shopy
author: Dev_Dome
description: Kommt später
authors: [Dev_Dome]
depend: [Citizens, RyseInventory, ItemsAdder]
api-version: '1.20'
commands:
  setspawn:
  LoadDefaultValue:
  setnpcspawn:
  shop:
  spawn:
  setshopzone:
  setshopposition:
  ressouren:
  money:
  setressource:
  itemlager:
  zeigewelten:
  ladewelt:
  welttp:
  adddungeon:
  setdungeon:
  dungeon:
  npcreload: